In [1]:
#install keras,tensorflow and imutils

import  numpy as np
import os
import matplotlib.pyplot as plt
from imutils import paths

In [2]:
from tensorflow.keras.applications import MobileNetV2

In [3]:
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import AveragePooling2D
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Input
from tensorflow.keras.models import Model

In [4]:
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

In [5]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import load_img

In [6]:
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import classification_report

In [7]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split

In [8]:
Data=r'C:\Users\AAVEJ\Desktop\Mtech\MLP_project\DataSet3'
path=list(paths.list_images(Data))

In [9]:
path

['C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\100.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\101.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\102.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\104.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\105.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\106.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\107.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\108.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\109.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\110.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\111.jpg',
 'C:\\Users\\AAVEJ\\Desktop\\Mtech\\MLP_project\\DataSet3\\without_mask\\112.jpg',
 'C:

In [10]:
data=[]
catogr=[]

for i in path:
    label=i.split(os.path.sep)[-2]
    catogr.append(label)
    image=load_img(i,target_size=(224,224))
    image=img_to_array(image)
    image=preprocess_input(image)
    data.append(image)

In [11]:
data

[array([[[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 0.9843137 ],
         [1.        , 1.        , 0.9843137 ],
         [0.9764706 , 1.        , 0.9843137 ]],
 
        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 0.99215686, 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],
 
        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         ...,
         [1.        , 1.        , 1.        ],
         [1.        , 0.99215686, 1.        ],
         [1.        , 0.9843137 , 1.        ]],
 
        ...,
 
        [[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.     

In [12]:
catogr #its our depedent variable

['without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask',
 'without_mask

In [13]:
data=np.array(data,dtype='float32') 
catogr=np.array(catogr)

In [14]:
data.shape

(8225, 224, 224, 3)

In [15]:
data

array([[[[ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         ...,
         [ 1.        ,  1.        ,  0.9843137 ],
         [ 1.        ,  1.        ,  0.9843137 ],
         [ 0.9764706 ,  1.        ,  0.9843137 ]],

        [[ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         ...,
         [ 1.        ,  0.99215686,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ]],

        [[ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  1.        ,  1.        ],
         ...,
         [ 1.        ,  1.        ,  1.        ],
         [ 1.        ,  0.99215686,  1.        ],
         [ 1.        ,  0.9843137 ,  1.        ]],

        ...,

        [[ 1.        ,  1.        ,  1

In [16]:
catogr

array(['without_mask', 'without_mask', 'without_mask', ..., 'with_mask',
       'with_mask', 'with_mask'], dtype='<U12')

In [17]:
lb=LabelBinarizer()
catogr=lb.fit_transform(catogr)
catogr=to_categorical(catogr)

In [18]:
catogr

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [19]:
train_X,test_X,train_Y,test_Y=train_test_split(data,catogr,test_size=0.25,random_state=10,stratify=catogr)

In [20]:
train_X


array([[[[ 0.2313726 ,  0.2313726 ,  0.2313726 ],
         [ 0.2313726 ,  0.2313726 ,  0.2313726 ],
         [ 0.26274514,  0.26274514,  0.26274514],
         ...,
         [ 0.30196083,  0.30196083,  0.30196083],
         [ 0.30196083,  0.30196083,  0.30196083],
         [ 0.3176471 ,  0.3176471 ,  0.3176471 ]],

        [[ 0.23921573,  0.23921573,  0.23921573],
         [ 0.24705887,  0.24705887,  0.24705887],
         [ 0.24705887,  0.24705887,  0.24705887],
         ...,
         [ 0.2941177 ,  0.2941177 ,  0.2941177 ],
         [ 0.2941177 ,  0.2941177 ,  0.2941177 ],
         [ 0.26274514,  0.26274514,  0.26274514]],

        [[ 0.22352946,  0.22352946,  0.22352946],
         [ 0.23921573,  0.23921573,  0.23921573],
         [ 0.23921573,  0.23921573,  0.23921573],
         ...,
         [ 0.27843142,  0.27843142,  0.27843142],
         [ 0.27058828,  0.27058828,  0.27058828],
         [ 0.24705887,  0.24705887,  0.24705887]],

        ...,

        [[ 0.20000005,  0.20000005,  0

In [21]:
train_Y

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]], dtype=float32)

In [22]:
train_Y.shape

(6168, 2)

In [23]:
train_X.shape

(6168, 224, 224, 3)

In [24]:
test_X.shape

(2057, 224, 224, 3)

In [25]:
test_Y.shape

(2057, 2)

In [26]:
Img_generator=ImageDataGenerator(rotation_range=20,zoom_range=0.15,width_shift_range=0.2,height_shift_range=0.2,shear_range=0.15,horizontal_flip=True,vertical_flip=True,fill_mode='nearest')

In [27]:
basemodel=MobileNetV2(weights='imagenet',include_top=False,input_tensor=Input(shape=(224,224,3)))

In [28]:
basemodel.summary()

Model: "mobilenetv2_1.00_224"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 225, 225, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
_______________________________________________________________________________

Total params: 2,257,984
Trainable params: 2,223,872
Non-trainable params: 34,112
__________________________________________________________________________________________________


In [29]:
headmodel=basemodel.output
headmodel=AveragePooling2D(pool_size=(7,7))(headmodel)
headmodel=Flatten(name='Flatten')(headmodel)
headmodel=Dense(128,activation='relu')(headmodel)
headmodel=Dropout(0.5)(headmodel)
headmodel=Dense(2,activation='softmax')(headmodel)
model=Model(inputs=basemodel.input,outputs=headmodel)

In [30]:
for layer in basemodel.layers:
    layer.trainable=False

In [31]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
Conv1_pad (ZeroPadding2D)       (None, 225, 225, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
Conv1 (Conv2D)                  (None, 112, 112, 32) 864         Conv1_pad[0][0]                  
__________________________________________________________________________________________________
bn_Conv1 (BatchNormalization)   (None, 112, 112, 32) 128         Conv1[0][0]                      
______________________________________________________________________________________________

In [32]:
lr=0.0001
Epc=20
Bs=11

opt=Adam(lr=lr,decay=lr/Epc)
model.compile(loss='binary_crossentropy',optimizer=opt,metrics=['accuracy'])

U=model.fit(
      Img_generator.flow(train_X,train_Y,batch_size=Bs),
      steps_per_epoch=len(train_X)//Bs,
      validation_data=(test_X,test_Y),
      validation_steps=len(test_X)//Bs,
      epochs=Epc
)

model.save(r'C:\Users\AAVEJ\Desktop\Mtech\MLP_project\umar.model')

Epoch 1/20
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
560/560 [==============================] - ETA: 0s - loss: 0.0976 - accuracy: 0.9648WARNING:tensorflow:AutoGraph could not transform <function Model.make_test_function.<locals>.test_function at 0x000002F4142F3488> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and atta

In [33]:
predict=model.predict(test_X,batch_size=Bs)
predict=np.argmax(predict,axis=1)
print(classification_report(test_Y.argmax(axis=1),predict,target_names=lb.classes_))

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Bad argument number for Name: 4, expecting 3
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
              precision    recall  f1-score   support

   with_mask       1.00      1.00      1.00      1064
without_mask       1.00      1.00      1.00       993

    accuracy                           1.00      2057
   macro avg       1.00      1.00      1.00      2057
weighted avg       1.00      1.00      1.00      2057

